name       : libstrangle
version    : 0.1.0
release    : 2
source     :
    - https://gitlab.com/torkel104/libstrangle/-/archive/0.1.0/libstrangle-0.1.0.tar.gz : ee4b4680f6daf97ad4860ab5ee3771df8cb197de34ff25d85d6474a1beb6172e
license    : GPL-3.0-or-later
component  : desktop.library
summary    : Frame rate limiter for Linux/OpenGL
description: |
    Cap the FPS (frames per second) of a chosen game by including libstrangle.so in LD_PRELOAD.
builddeps  :
    - pkgconfig32(gl)
    - glibc-32bit-devel
rundeps    :
    - vulkan-32bit
patterns   :
    - /usr/lib32/*.so
    - /usr/lib64/*.so
setup      : |
    %patch -p1 < $pkgfiles/0001-Solus-build-configuration.patch
build      : |
    %make
install    : |
    %make_install
