name       : libstrangle
version    : 0.0.4
release    : 1
source     :
    - https://gitlab.com/torkel104/libstrangle/-/archive/0.0.4/libstrangle-0.0.4.tar.gz : a14ef2d4c25245bb8be5cfc6c129b4d63c4b7be10f07cee828f33055997469af
license    : GPL-3.0-or-later
component  : desktop.library
summary    : Frame rate limiter for Linux/OpenGL
description: |
    Cap the FPS (frames per second) of a chosen game by including libstrangle.so in LD_PRELOAD.
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
rundeps    :
    - vulkan-32bit
patterns   :
    - /usr/lib32/*.so
    - /usr/lib64/*.so
setup      : |
    %apply_patches
build      : |
    %make
install    : |
    %make_install
