name       : libstrangle
version    : 0.1.1
release    : 3
source     :
    - https://gitlab.com/torkel104/libstrangle/-/archive/0.1.1/libstrangle-0.1.1.tar.gz : 8413f260ce1ab15cd38752f67650dee2f822f858d384d6c0784a9428c23cd105
license    : GPL-3.0-or-later
component  : desktop.library
summary    : Frame rate limiter for Linux/OpenGL
description: |
    Cap the FPS (frames per second) of a chosen game by including libstrangle.so in LD_PRELOAD.
builddeps  :
    - pkgconfig32(gl)
    - glibc-32bit-devel
rundeps    :
    - vulkan-32bit
patterns   :
    - /usr/lib32/*.so
    - /usr/lib64/*.so
setup      : |
    %patch -p1 < $pkgfiles/0001-Solus-build-configuration.patch
build      : |
    %make
install    : |
    %make_install
